import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   ALTER TYPE "public"."enum_pages_blocks_heading_appearance" ADD VALUE 'h5';
  ALTER TYPE "public"."enum_pages_blocks_heading_appearance" ADD VALUE 'h6';
  ALTER TYPE "public"."enum_pages_blocks_content_section_columns_padding" ADD VALUE 'large';
  ALTER TYPE "public"."enum__pages_v_blocks_heading_appearance" ADD VALUE 'h5';
  ALTER TYPE "public"."enum__pages_v_blocks_heading_appearance" ADD VALUE 'h6';
  ALTER TYPE "public"."enum__pages_v_blocks_content_section_columns_padding" ADD VALUE 'large';
  ALTER TYPE "public"."enum_articles_blocks_heading_appearance" ADD VALUE 'h5';
  ALTER TYPE "public"."enum_articles_blocks_heading_appearance" ADD VALUE 'h6';
  ALTER TYPE "public"."enum_articles_blocks_content_section_columns_padding" ADD VALUE 'large';
  ALTER TYPE "public"."enum__articles_v_blocks_heading_appearance" ADD VALUE 'h5';
  ALTER TYPE "public"."enum__articles_v_blocks_heading_appearance" ADD VALUE 'h6';
  ALTER TYPE "public"."enum__articles_v_blocks_content_section_columns_padding" ADD VALUE 'large';
  ALTER TYPE "public"."enum_hubs_blocks_heading_appearance" ADD VALUE 'h5';
  ALTER TYPE "public"."enum_hubs_blocks_heading_appearance" ADD VALUE 'h6';
  ALTER TYPE "public"."enum_hubs_blocks_content_section_columns_padding" ADD VALUE 'large';
  ALTER TYPE "public"."enum__hubs_v_blocks_heading_appearance" ADD VALUE 'h5';
  ALTER TYPE "public"."enum__hubs_v_blocks_heading_appearance" ADD VALUE 'h6';
  ALTER TYPE "public"."enum__hubs_v_blocks_content_section_columns_padding" ADD VALUE 'large';
  ALTER TYPE "public"."enum_venues_blocks_heading_appearance" ADD VALUE 'h5';
  ALTER TYPE "public"."enum_venues_blocks_heading_appearance" ADD VALUE 'h6';
  ALTER TYPE "public"."enum_venues_blocks_content_section_columns_padding" ADD VALUE 'large';
  ALTER TYPE "public"."enum__venues_v_blocks_heading_appearance" ADD VALUE 'h5';
  ALTER TYPE "public"."enum__venues_v_blocks_heading_appearance" ADD VALUE 'h6';
  ALTER TYPE "public"."enum__venues_v_blocks_content_section_columns_padding" ADD VALUE 'large';
  ALTER TYPE "public"."enum_learning_videos_blocks_heading_appearance" ADD VALUE 'h5';
  ALTER TYPE "public"."enum_learning_videos_blocks_heading_appearance" ADD VALUE 'h6';
  ALTER TYPE "public"."enum_learning_videos_blocks_content_section_columns_padding" ADD VALUE 'large';
  ALTER TYPE "public"."enum__learning_videos_v_blocks_heading_appearance" ADD VALUE 'h5';
  ALTER TYPE "public"."enum__learning_videos_v_blocks_heading_appearance" ADD VALUE 'h6';
  ALTER TYPE "public"."enum__learning_videos_v_blocks_content_section_columns_padding" ADD VALUE 'large';`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "pages_blocks_heading" ALTER COLUMN "appearance" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_heading" ALTER COLUMN "appearance" SET DEFAULT 'h2'::text;
  DROP TYPE "public"."enum_pages_blocks_heading_appearance";
  CREATE TYPE "public"."enum_pages_blocks_heading_appearance" AS ENUM('h1', 'h2', 'h3', 'h4');
  ALTER TABLE "pages_blocks_heading" ALTER COLUMN "appearance" SET DEFAULT 'h2'::"public"."enum_pages_blocks_heading_appearance";
  ALTER TABLE "pages_blocks_heading" ALTER COLUMN "appearance" SET DATA TYPE "public"."enum_pages_blocks_heading_appearance" USING "appearance"::"public"."enum_pages_blocks_heading_appearance";
  ALTER TABLE "pages_blocks_content_section_columns" ALTER COLUMN "padding" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_content_section_columns" ALTER COLUMN "padding" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum_pages_blocks_content_section_columns_padding";
  CREATE TYPE "public"."enum_pages_blocks_content_section_columns_padding" AS ENUM('none', 'medium');
  ALTER TABLE "pages_blocks_content_section_columns" ALTER COLUMN "padding" SET DEFAULT 'none'::"public"."enum_pages_blocks_content_section_columns_padding";
  ALTER TABLE "pages_blocks_content_section_columns" ALTER COLUMN "padding" SET DATA TYPE "public"."enum_pages_blocks_content_section_columns_padding" USING "padding"::"public"."enum_pages_blocks_content_section_columns_padding";
  ALTER TABLE "_pages_v_blocks_heading" ALTER COLUMN "appearance" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_heading" ALTER COLUMN "appearance" SET DEFAULT 'h2'::text;
  DROP TYPE "public"."enum__pages_v_blocks_heading_appearance";
  CREATE TYPE "public"."enum__pages_v_blocks_heading_appearance" AS ENUM('h1', 'h2', 'h3', 'h4');
  ALTER TABLE "_pages_v_blocks_heading" ALTER COLUMN "appearance" SET DEFAULT 'h2'::"public"."enum__pages_v_blocks_heading_appearance";
  ALTER TABLE "_pages_v_blocks_heading" ALTER COLUMN "appearance" SET DATA TYPE "public"."enum__pages_v_blocks_heading_appearance" USING "appearance"::"public"."enum__pages_v_blocks_heading_appearance";
  ALTER TABLE "_pages_v_blocks_content_section_columns" ALTER COLUMN "padding" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_content_section_columns" ALTER COLUMN "padding" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum__pages_v_blocks_content_section_columns_padding";
  CREATE TYPE "public"."enum__pages_v_blocks_content_section_columns_padding" AS ENUM('none', 'medium');
  ALTER TABLE "_pages_v_blocks_content_section_columns" ALTER COLUMN "padding" SET DEFAULT 'none'::"public"."enum__pages_v_blocks_content_section_columns_padding";
  ALTER TABLE "_pages_v_blocks_content_section_columns" ALTER COLUMN "padding" SET DATA TYPE "public"."enum__pages_v_blocks_content_section_columns_padding" USING "padding"::"public"."enum__pages_v_blocks_content_section_columns_padding";
  ALTER TABLE "articles_blocks_heading" ALTER COLUMN "appearance" SET DATA TYPE text;
  ALTER TABLE "articles_blocks_heading" ALTER COLUMN "appearance" SET DEFAULT 'h2'::text;
  DROP TYPE "public"."enum_articles_blocks_heading_appearance";
  CREATE TYPE "public"."enum_articles_blocks_heading_appearance" AS ENUM('h1', 'h2', 'h3', 'h4');
  ALTER TABLE "articles_blocks_heading" ALTER COLUMN "appearance" SET DEFAULT 'h2'::"public"."enum_articles_blocks_heading_appearance";
  ALTER TABLE "articles_blocks_heading" ALTER COLUMN "appearance" SET DATA TYPE "public"."enum_articles_blocks_heading_appearance" USING "appearance"::"public"."enum_articles_blocks_heading_appearance";
  ALTER TABLE "articles_blocks_content_section_columns" ALTER COLUMN "padding" SET DATA TYPE text;
  ALTER TABLE "articles_blocks_content_section_columns" ALTER COLUMN "padding" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum_articles_blocks_content_section_columns_padding";
  CREATE TYPE "public"."enum_articles_blocks_content_section_columns_padding" AS ENUM('none', 'medium');
  ALTER TABLE "articles_blocks_content_section_columns" ALTER COLUMN "padding" SET DEFAULT 'none'::"public"."enum_articles_blocks_content_section_columns_padding";
  ALTER TABLE "articles_blocks_content_section_columns" ALTER COLUMN "padding" SET DATA TYPE "public"."enum_articles_blocks_content_section_columns_padding" USING "padding"::"public"."enum_articles_blocks_content_section_columns_padding";
  ALTER TABLE "_articles_v_blocks_heading" ALTER COLUMN "appearance" SET DATA TYPE text;
  ALTER TABLE "_articles_v_blocks_heading" ALTER COLUMN "appearance" SET DEFAULT 'h2'::text;
  DROP TYPE "public"."enum__articles_v_blocks_heading_appearance";
  CREATE TYPE "public"."enum__articles_v_blocks_heading_appearance" AS ENUM('h1', 'h2', 'h3', 'h4');
  ALTER TABLE "_articles_v_blocks_heading" ALTER COLUMN "appearance" SET DEFAULT 'h2'::"public"."enum__articles_v_blocks_heading_appearance";
  ALTER TABLE "_articles_v_blocks_heading" ALTER COLUMN "appearance" SET DATA TYPE "public"."enum__articles_v_blocks_heading_appearance" USING "appearance"::"public"."enum__articles_v_blocks_heading_appearance";
  ALTER TABLE "_articles_v_blocks_content_section_columns" ALTER COLUMN "padding" SET DATA TYPE text;
  ALTER TABLE "_articles_v_blocks_content_section_columns" ALTER COLUMN "padding" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum__articles_v_blocks_content_section_columns_padding";
  CREATE TYPE "public"."enum__articles_v_blocks_content_section_columns_padding" AS ENUM('none', 'medium');
  ALTER TABLE "_articles_v_blocks_content_section_columns" ALTER COLUMN "padding" SET DEFAULT 'none'::"public"."enum__articles_v_blocks_content_section_columns_padding";
  ALTER TABLE "_articles_v_blocks_content_section_columns" ALTER COLUMN "padding" SET DATA TYPE "public"."enum__articles_v_blocks_content_section_columns_padding" USING "padding"::"public"."enum__articles_v_blocks_content_section_columns_padding";
  ALTER TABLE "hubs_blocks_heading" ALTER COLUMN "appearance" SET DATA TYPE text;
  ALTER TABLE "hubs_blocks_heading" ALTER COLUMN "appearance" SET DEFAULT 'h2'::text;
  DROP TYPE "public"."enum_hubs_blocks_heading_appearance";
  CREATE TYPE "public"."enum_hubs_blocks_heading_appearance" AS ENUM('h1', 'h2', 'h3', 'h4');
  ALTER TABLE "hubs_blocks_heading" ALTER COLUMN "appearance" SET DEFAULT 'h2'::"public"."enum_hubs_blocks_heading_appearance";
  ALTER TABLE "hubs_blocks_heading" ALTER COLUMN "appearance" SET DATA TYPE "public"."enum_hubs_blocks_heading_appearance" USING "appearance"::"public"."enum_hubs_blocks_heading_appearance";
  ALTER TABLE "hubs_blocks_content_section_columns" ALTER COLUMN "padding" SET DATA TYPE text;
  ALTER TABLE "hubs_blocks_content_section_columns" ALTER COLUMN "padding" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum_hubs_blocks_content_section_columns_padding";
  CREATE TYPE "public"."enum_hubs_blocks_content_section_columns_padding" AS ENUM('none', 'medium');
  ALTER TABLE "hubs_blocks_content_section_columns" ALTER COLUMN "padding" SET DEFAULT 'none'::"public"."enum_hubs_blocks_content_section_columns_padding";
  ALTER TABLE "hubs_blocks_content_section_columns" ALTER COLUMN "padding" SET DATA TYPE "public"."enum_hubs_blocks_content_section_columns_padding" USING "padding"::"public"."enum_hubs_blocks_content_section_columns_padding";
  ALTER TABLE "_hubs_v_blocks_heading" ALTER COLUMN "appearance" SET DATA TYPE text;
  ALTER TABLE "_hubs_v_blocks_heading" ALTER COLUMN "appearance" SET DEFAULT 'h2'::text;
  DROP TYPE "public"."enum__hubs_v_blocks_heading_appearance";
  CREATE TYPE "public"."enum__hubs_v_blocks_heading_appearance" AS ENUM('h1', 'h2', 'h3', 'h4');
  ALTER TABLE "_hubs_v_blocks_heading" ALTER COLUMN "appearance" SET DEFAULT 'h2'::"public"."enum__hubs_v_blocks_heading_appearance";
  ALTER TABLE "_hubs_v_blocks_heading" ALTER COLUMN "appearance" SET DATA TYPE "public"."enum__hubs_v_blocks_heading_appearance" USING "appearance"::"public"."enum__hubs_v_blocks_heading_appearance";
  ALTER TABLE "_hubs_v_blocks_content_section_columns" ALTER COLUMN "padding" SET DATA TYPE text;
  ALTER TABLE "_hubs_v_blocks_content_section_columns" ALTER COLUMN "padding" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum__hubs_v_blocks_content_section_columns_padding";
  CREATE TYPE "public"."enum__hubs_v_blocks_content_section_columns_padding" AS ENUM('none', 'medium');
  ALTER TABLE "_hubs_v_blocks_content_section_columns" ALTER COLUMN "padding" SET DEFAULT 'none'::"public"."enum__hubs_v_blocks_content_section_columns_padding";
  ALTER TABLE "_hubs_v_blocks_content_section_columns" ALTER COLUMN "padding" SET DATA TYPE "public"."enum__hubs_v_blocks_content_section_columns_padding" USING "padding"::"public"."enum__hubs_v_blocks_content_section_columns_padding";
  ALTER TABLE "venues_blocks_heading" ALTER COLUMN "appearance" SET DATA TYPE text;
  ALTER TABLE "venues_blocks_heading" ALTER COLUMN "appearance" SET DEFAULT 'h2'::text;
  DROP TYPE "public"."enum_venues_blocks_heading_appearance";
  CREATE TYPE "public"."enum_venues_blocks_heading_appearance" AS ENUM('h1', 'h2', 'h3', 'h4');
  ALTER TABLE "venues_blocks_heading" ALTER COLUMN "appearance" SET DEFAULT 'h2'::"public"."enum_venues_blocks_heading_appearance";
  ALTER TABLE "venues_blocks_heading" ALTER COLUMN "appearance" SET DATA TYPE "public"."enum_venues_blocks_heading_appearance" USING "appearance"::"public"."enum_venues_blocks_heading_appearance";
  ALTER TABLE "venues_blocks_content_section_columns" ALTER COLUMN "padding" SET DATA TYPE text;
  ALTER TABLE "venues_blocks_content_section_columns" ALTER COLUMN "padding" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum_venues_blocks_content_section_columns_padding";
  CREATE TYPE "public"."enum_venues_blocks_content_section_columns_padding" AS ENUM('none', 'medium');
  ALTER TABLE "venues_blocks_content_section_columns" ALTER COLUMN "padding" SET DEFAULT 'none'::"public"."enum_venues_blocks_content_section_columns_padding";
  ALTER TABLE "venues_blocks_content_section_columns" ALTER COLUMN "padding" SET DATA TYPE "public"."enum_venues_blocks_content_section_columns_padding" USING "padding"::"public"."enum_venues_blocks_content_section_columns_padding";
  ALTER TABLE "_venues_v_blocks_heading" ALTER COLUMN "appearance" SET DATA TYPE text;
  ALTER TABLE "_venues_v_blocks_heading" ALTER COLUMN "appearance" SET DEFAULT 'h2'::text;
  DROP TYPE "public"."enum__venues_v_blocks_heading_appearance";
  CREATE TYPE "public"."enum__venues_v_blocks_heading_appearance" AS ENUM('h1', 'h2', 'h3', 'h4');
  ALTER TABLE "_venues_v_blocks_heading" ALTER COLUMN "appearance" SET DEFAULT 'h2'::"public"."enum__venues_v_blocks_heading_appearance";
  ALTER TABLE "_venues_v_blocks_heading" ALTER COLUMN "appearance" SET DATA TYPE "public"."enum__venues_v_blocks_heading_appearance" USING "appearance"::"public"."enum__venues_v_blocks_heading_appearance";
  ALTER TABLE "_venues_v_blocks_content_section_columns" ALTER COLUMN "padding" SET DATA TYPE text;
  ALTER TABLE "_venues_v_blocks_content_section_columns" ALTER COLUMN "padding" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum__venues_v_blocks_content_section_columns_padding";
  CREATE TYPE "public"."enum__venues_v_blocks_content_section_columns_padding" AS ENUM('none', 'medium');
  ALTER TABLE "_venues_v_blocks_content_section_columns" ALTER COLUMN "padding" SET DEFAULT 'none'::"public"."enum__venues_v_blocks_content_section_columns_padding";
  ALTER TABLE "_venues_v_blocks_content_section_columns" ALTER COLUMN "padding" SET DATA TYPE "public"."enum__venues_v_blocks_content_section_columns_padding" USING "padding"::"public"."enum__venues_v_blocks_content_section_columns_padding";
  ALTER TABLE "learning_videos_blocks_heading" ALTER COLUMN "appearance" SET DATA TYPE text;
  ALTER TABLE "learning_videos_blocks_heading" ALTER COLUMN "appearance" SET DEFAULT 'h2'::text;
  DROP TYPE "public"."enum_learning_videos_blocks_heading_appearance";
  CREATE TYPE "public"."enum_learning_videos_blocks_heading_appearance" AS ENUM('h1', 'h2', 'h3', 'h4');
  ALTER TABLE "learning_videos_blocks_heading" ALTER COLUMN "appearance" SET DEFAULT 'h2'::"public"."enum_learning_videos_blocks_heading_appearance";
  ALTER TABLE "learning_videos_blocks_heading" ALTER COLUMN "appearance" SET DATA TYPE "public"."enum_learning_videos_blocks_heading_appearance" USING "appearance"::"public"."enum_learning_videos_blocks_heading_appearance";
  ALTER TABLE "learning_videos_blocks_content_section_columns" ALTER COLUMN "padding" SET DATA TYPE text;
  ALTER TABLE "learning_videos_blocks_content_section_columns" ALTER COLUMN "padding" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum_learning_videos_blocks_content_section_columns_padding";
  CREATE TYPE "public"."enum_learning_videos_blocks_content_section_columns_padding" AS ENUM('none', 'medium');
  ALTER TABLE "learning_videos_blocks_content_section_columns" ALTER COLUMN "padding" SET DEFAULT 'none'::"public"."enum_learning_videos_blocks_content_section_columns_padding";
  ALTER TABLE "learning_videos_blocks_content_section_columns" ALTER COLUMN "padding" SET DATA TYPE "public"."enum_learning_videos_blocks_content_section_columns_padding" USING "padding"::"public"."enum_learning_videos_blocks_content_section_columns_padding";
  ALTER TABLE "_learning_videos_v_blocks_heading" ALTER COLUMN "appearance" SET DATA TYPE text;
  ALTER TABLE "_learning_videos_v_blocks_heading" ALTER COLUMN "appearance" SET DEFAULT 'h2'::text;
  DROP TYPE "public"."enum__learning_videos_v_blocks_heading_appearance";
  CREATE TYPE "public"."enum__learning_videos_v_blocks_heading_appearance" AS ENUM('h1', 'h2', 'h3', 'h4');
  ALTER TABLE "_learning_videos_v_blocks_heading" ALTER COLUMN "appearance" SET DEFAULT 'h2'::"public"."enum__learning_videos_v_blocks_heading_appearance";
  ALTER TABLE "_learning_videos_v_blocks_heading" ALTER COLUMN "appearance" SET DATA TYPE "public"."enum__learning_videos_v_blocks_heading_appearance" USING "appearance"::"public"."enum__learning_videos_v_blocks_heading_appearance";
  ALTER TABLE "_learning_videos_v_blocks_content_section_columns" ALTER COLUMN "padding" SET DATA TYPE text;
  ALTER TABLE "_learning_videos_v_blocks_content_section_columns" ALTER COLUMN "padding" SET DEFAULT 'none'::text;
  DROP TYPE "public"."enum__learning_videos_v_blocks_content_section_columns_padding";
  CREATE TYPE "public"."enum__learning_videos_v_blocks_content_section_columns_padding" AS ENUM('none', 'medium');
  ALTER TABLE "_learning_videos_v_blocks_content_section_columns" ALTER COLUMN "padding" SET DEFAULT 'none'::"public"."enum__learning_videos_v_blocks_content_section_columns_padding";
  ALTER TABLE "_learning_videos_v_blocks_content_section_columns" ALTER COLUMN "padding" SET DATA TYPE "public"."enum__learning_videos_v_blocks_content_section_columns_padding" USING "padding"::"public"."enum__learning_videos_v_blocks_content_section_columns_padding";`)
}
