import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   ALTER TYPE "public"."enum_pages_blocks_trayport_hero_actions_icon" ADD VALUE 'forward' BEFORE 'people';
  ALTER TYPE "public"."enum_pages_blocks_actions_actions_icon" ADD VALUE 'forward' BEFORE 'people';
  ALTER TYPE "public"."enum_pages_blocks_feature_list_items_action_icon" ADD VALUE 'forward' BEFORE 'people';
  ALTER TYPE "public"."enum_pages_blocks_market_coverage_actions_icon" ADD VALUE 'forward' BEFORE 'people';
  ALTER TYPE "public"."enum__pages_v_blocks_trayport_hero_actions_icon" ADD VALUE 'forward' BEFORE 'people';
  ALTER TYPE "public"."enum__pages_v_blocks_actions_actions_icon" ADD VALUE 'forward' BEFORE 'people';
  ALTER TYPE "public"."enum__pages_v_blocks_feature_list_items_action_icon" ADD VALUE 'forward' BEFORE 'people';
  ALTER TYPE "public"."enum__pages_v_blocks_market_coverage_actions_icon" ADD VALUE 'forward' BEFORE 'people';
  ALTER TYPE "public"."enum_articles_blocks_trayport_hero_actions_icon" ADD VALUE 'forward' BEFORE 'people';
  ALTER TYPE "public"."enum_articles_blocks_actions_actions_icon" ADD VALUE 'forward' BEFORE 'people';
  ALTER TYPE "public"."enum_articles_blocks_feature_list_items_action_icon" ADD VALUE 'forward' BEFORE 'people';
  ALTER TYPE "public"."enum_articles_blocks_market_coverage_actions_icon" ADD VALUE 'forward' BEFORE 'people';
  ALTER TYPE "public"."enum__articles_v_blocks_trayport_hero_actions_icon" ADD VALUE 'forward' BEFORE 'people';
  ALTER TYPE "public"."enum__articles_v_blocks_actions_actions_icon" ADD VALUE 'forward' BEFORE 'people';
  ALTER TYPE "public"."enum__articles_v_blocks_feature_list_items_action_icon" ADD VALUE 'forward' BEFORE 'people';
  ALTER TYPE "public"."enum__articles_v_blocks_market_coverage_actions_icon" ADD VALUE 'forward' BEFORE 'people';
  ALTER TYPE "public"."enum_hubs_blocks_trayport_hero_actions_icon" ADD VALUE 'forward' BEFORE 'people';
  ALTER TYPE "public"."enum_hubs_blocks_actions_actions_icon" ADD VALUE 'forward' BEFORE 'people';
  ALTER TYPE "public"."enum_hubs_blocks_feature_list_items_action_icon" ADD VALUE 'forward' BEFORE 'people';
  ALTER TYPE "public"."enum_hubs_blocks_market_coverage_actions_icon" ADD VALUE 'forward' BEFORE 'people';
  ALTER TYPE "public"."enum__hubs_v_blocks_trayport_hero_actions_icon" ADD VALUE 'forward' BEFORE 'people';
  ALTER TYPE "public"."enum__hubs_v_blocks_actions_actions_icon" ADD VALUE 'forward' BEFORE 'people';
  ALTER TYPE "public"."enum__hubs_v_blocks_feature_list_items_action_icon" ADD VALUE 'forward' BEFORE 'people';
  ALTER TYPE "public"."enum__hubs_v_blocks_market_coverage_actions_icon" ADD VALUE 'forward' BEFORE 'people';
  ALTER TYPE "public"."enum_venues_blocks_trayport_hero_actions_icon" ADD VALUE 'forward' BEFORE 'people';
  ALTER TYPE "public"."enum_venues_blocks_actions_actions_icon" ADD VALUE 'forward' BEFORE 'people';
  ALTER TYPE "public"."enum_venues_blocks_feature_list_items_action_icon" ADD VALUE 'forward' BEFORE 'people';
  ALTER TYPE "public"."enum_venues_blocks_market_coverage_actions_icon" ADD VALUE 'forward' BEFORE 'people';
  ALTER TYPE "public"."enum__venues_v_blocks_trayport_hero_actions_icon" ADD VALUE 'forward' BEFORE 'people';
  ALTER TYPE "public"."enum__venues_v_blocks_actions_actions_icon" ADD VALUE 'forward' BEFORE 'people';
  ALTER TYPE "public"."enum__venues_v_blocks_feature_list_items_action_icon" ADD VALUE 'forward' BEFORE 'people';
  ALTER TYPE "public"."enum__venues_v_blocks_market_coverage_actions_icon" ADD VALUE 'forward' BEFORE 'people';
  ALTER TYPE "public"."enum_learning_videos_blocks_trayport_hero_actions_icon" ADD VALUE 'forward' BEFORE 'people';
  ALTER TYPE "public"."enum_learning_videos_blocks_actions_actions_icon" ADD VALUE 'forward' BEFORE 'people';
  ALTER TYPE "public"."enum_learning_videos_blocks_feature_list_items_action_icon" ADD VALUE 'forward' BEFORE 'people';
  ALTER TYPE "public"."enum_learning_videos_blocks_market_coverage_actions_icon" ADD VALUE 'forward' BEFORE 'people';
  ALTER TYPE "public"."enum__learning_videos_v_blocks_trayport_hero_actions_icon" ADD VALUE 'forward' BEFORE 'people';
  ALTER TYPE "public"."enum__learning_videos_v_blocks_actions_actions_icon" ADD VALUE 'forward' BEFORE 'people';
  ALTER TYPE "public"."enum__learning_videos_v_blocks_feature_list_items_action_icon" ADD VALUE 'forward' BEFORE 'people';
  ALTER TYPE "public"."enum__learning_videos_v_blocks_market_coverage_actions_icon" ADD VALUE 'forward' BEFORE 'people';`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "pages_blocks_trayport_hero_actions" ALTER COLUMN "icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_pages_blocks_trayport_hero_actions_icon";
  CREATE TYPE "public"."enum_pages_blocks_trayport_hero_actions_icon" AS ENUM('arrowRight', 'chart', 'europe', 'people', 'play', 'settings');
  ALTER TABLE "pages_blocks_trayport_hero_actions" ALTER COLUMN "icon" SET DATA TYPE "public"."enum_pages_blocks_trayport_hero_actions_icon" USING "icon"::"public"."enum_pages_blocks_trayport_hero_actions_icon";
  ALTER TABLE "pages_blocks_actions_actions" ALTER COLUMN "icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_pages_blocks_actions_actions_icon";
  CREATE TYPE "public"."enum_pages_blocks_actions_actions_icon" AS ENUM('arrowRight', 'chart', 'europe', 'people', 'play', 'settings');
  ALTER TABLE "pages_blocks_actions_actions" ALTER COLUMN "icon" SET DATA TYPE "public"."enum_pages_blocks_actions_actions_icon" USING "icon"::"public"."enum_pages_blocks_actions_actions_icon";
  ALTER TABLE "pages_blocks_feature_list_items" ALTER COLUMN "action_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_pages_blocks_feature_list_items_action_icon";
  CREATE TYPE "public"."enum_pages_blocks_feature_list_items_action_icon" AS ENUM('arrowRight', 'chart', 'europe', 'people', 'play', 'settings');
  ALTER TABLE "pages_blocks_feature_list_items" ALTER COLUMN "action_icon" SET DATA TYPE "public"."enum_pages_blocks_feature_list_items_action_icon" USING "action_icon"::"public"."enum_pages_blocks_feature_list_items_action_icon";
  ALTER TABLE "pages_blocks_market_coverage_actions" ALTER COLUMN "icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_pages_blocks_market_coverage_actions_icon";
  CREATE TYPE "public"."enum_pages_blocks_market_coverage_actions_icon" AS ENUM('arrowRight', 'chart', 'europe', 'people', 'play', 'settings');
  ALTER TABLE "pages_blocks_market_coverage_actions" ALTER COLUMN "icon" SET DATA TYPE "public"."enum_pages_blocks_market_coverage_actions_icon" USING "icon"::"public"."enum_pages_blocks_market_coverage_actions_icon";
  ALTER TABLE "_pages_v_blocks_trayport_hero_actions" ALTER COLUMN "icon" SET DATA TYPE text;
  DROP TYPE "public"."enum__pages_v_blocks_trayport_hero_actions_icon";
  CREATE TYPE "public"."enum__pages_v_blocks_trayport_hero_actions_icon" AS ENUM('arrowRight', 'chart', 'europe', 'people', 'play', 'settings');
  ALTER TABLE "_pages_v_blocks_trayport_hero_actions" ALTER COLUMN "icon" SET DATA TYPE "public"."enum__pages_v_blocks_trayport_hero_actions_icon" USING "icon"::"public"."enum__pages_v_blocks_trayport_hero_actions_icon";
  ALTER TABLE "_pages_v_blocks_actions_actions" ALTER COLUMN "icon" SET DATA TYPE text;
  DROP TYPE "public"."enum__pages_v_blocks_actions_actions_icon";
  CREATE TYPE "public"."enum__pages_v_blocks_actions_actions_icon" AS ENUM('arrowRight', 'chart', 'europe', 'people', 'play', 'settings');
  ALTER TABLE "_pages_v_blocks_actions_actions" ALTER COLUMN "icon" SET DATA TYPE "public"."enum__pages_v_blocks_actions_actions_icon" USING "icon"::"public"."enum__pages_v_blocks_actions_actions_icon";
  ALTER TABLE "_pages_v_blocks_feature_list_items" ALTER COLUMN "action_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum__pages_v_blocks_feature_list_items_action_icon";
  CREATE TYPE "public"."enum__pages_v_blocks_feature_list_items_action_icon" AS ENUM('arrowRight', 'chart', 'europe', 'people', 'play', 'settings');
  ALTER TABLE "_pages_v_blocks_feature_list_items" ALTER COLUMN "action_icon" SET DATA TYPE "public"."enum__pages_v_blocks_feature_list_items_action_icon" USING "action_icon"::"public"."enum__pages_v_blocks_feature_list_items_action_icon";
  ALTER TABLE "_pages_v_blocks_market_coverage_actions" ALTER COLUMN "icon" SET DATA TYPE text;
  DROP TYPE "public"."enum__pages_v_blocks_market_coverage_actions_icon";
  CREATE TYPE "public"."enum__pages_v_blocks_market_coverage_actions_icon" AS ENUM('arrowRight', 'chart', 'europe', 'people', 'play', 'settings');
  ALTER TABLE "_pages_v_blocks_market_coverage_actions" ALTER COLUMN "icon" SET DATA TYPE "public"."enum__pages_v_blocks_market_coverage_actions_icon" USING "icon"::"public"."enum__pages_v_blocks_market_coverage_actions_icon";
  ALTER TABLE "articles_blocks_trayport_hero_actions" ALTER COLUMN "icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_articles_blocks_trayport_hero_actions_icon";
  CREATE TYPE "public"."enum_articles_blocks_trayport_hero_actions_icon" AS ENUM('arrowRight', 'chart', 'europe', 'people', 'play', 'settings');
  ALTER TABLE "articles_blocks_trayport_hero_actions" ALTER COLUMN "icon" SET DATA TYPE "public"."enum_articles_blocks_trayport_hero_actions_icon" USING "icon"::"public"."enum_articles_blocks_trayport_hero_actions_icon";
  ALTER TABLE "articles_blocks_actions_actions" ALTER COLUMN "icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_articles_blocks_actions_actions_icon";
  CREATE TYPE "public"."enum_articles_blocks_actions_actions_icon" AS ENUM('arrowRight', 'chart', 'europe', 'people', 'play', 'settings');
  ALTER TABLE "articles_blocks_actions_actions" ALTER COLUMN "icon" SET DATA TYPE "public"."enum_articles_blocks_actions_actions_icon" USING "icon"::"public"."enum_articles_blocks_actions_actions_icon";
  ALTER TABLE "articles_blocks_feature_list_items" ALTER COLUMN "action_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_articles_blocks_feature_list_items_action_icon";
  CREATE TYPE "public"."enum_articles_blocks_feature_list_items_action_icon" AS ENUM('arrowRight', 'chart', 'europe', 'people', 'play', 'settings');
  ALTER TABLE "articles_blocks_feature_list_items" ALTER COLUMN "action_icon" SET DATA TYPE "public"."enum_articles_blocks_feature_list_items_action_icon" USING "action_icon"::"public"."enum_articles_blocks_feature_list_items_action_icon";
  ALTER TABLE "articles_blocks_market_coverage_actions" ALTER COLUMN "icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_articles_blocks_market_coverage_actions_icon";
  CREATE TYPE "public"."enum_articles_blocks_market_coverage_actions_icon" AS ENUM('arrowRight', 'chart', 'europe', 'people', 'play', 'settings');
  ALTER TABLE "articles_blocks_market_coverage_actions" ALTER COLUMN "icon" SET DATA TYPE "public"."enum_articles_blocks_market_coverage_actions_icon" USING "icon"::"public"."enum_articles_blocks_market_coverage_actions_icon";
  ALTER TABLE "_articles_v_blocks_trayport_hero_actions" ALTER COLUMN "icon" SET DATA TYPE text;
  DROP TYPE "public"."enum__articles_v_blocks_trayport_hero_actions_icon";
  CREATE TYPE "public"."enum__articles_v_blocks_trayport_hero_actions_icon" AS ENUM('arrowRight', 'chart', 'europe', 'people', 'play', 'settings');
  ALTER TABLE "_articles_v_blocks_trayport_hero_actions" ALTER COLUMN "icon" SET DATA TYPE "public"."enum__articles_v_blocks_trayport_hero_actions_icon" USING "icon"::"public"."enum__articles_v_blocks_trayport_hero_actions_icon";
  ALTER TABLE "_articles_v_blocks_actions_actions" ALTER COLUMN "icon" SET DATA TYPE text;
  DROP TYPE "public"."enum__articles_v_blocks_actions_actions_icon";
  CREATE TYPE "public"."enum__articles_v_blocks_actions_actions_icon" AS ENUM('arrowRight', 'chart', 'europe', 'people', 'play', 'settings');
  ALTER TABLE "_articles_v_blocks_actions_actions" ALTER COLUMN "icon" SET DATA TYPE "public"."enum__articles_v_blocks_actions_actions_icon" USING "icon"::"public"."enum__articles_v_blocks_actions_actions_icon";
  ALTER TABLE "_articles_v_blocks_feature_list_items" ALTER COLUMN "action_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum__articles_v_blocks_feature_list_items_action_icon";
  CREATE TYPE "public"."enum__articles_v_blocks_feature_list_items_action_icon" AS ENUM('arrowRight', 'chart', 'europe', 'people', 'play', 'settings');
  ALTER TABLE "_articles_v_blocks_feature_list_items" ALTER COLUMN "action_icon" SET DATA TYPE "public"."enum__articles_v_blocks_feature_list_items_action_icon" USING "action_icon"::"public"."enum__articles_v_blocks_feature_list_items_action_icon";
  ALTER TABLE "_articles_v_blocks_market_coverage_actions" ALTER COLUMN "icon" SET DATA TYPE text;
  DROP TYPE "public"."enum__articles_v_blocks_market_coverage_actions_icon";
  CREATE TYPE "public"."enum__articles_v_blocks_market_coverage_actions_icon" AS ENUM('arrowRight', 'chart', 'europe', 'people', 'play', 'settings');
  ALTER TABLE "_articles_v_blocks_market_coverage_actions" ALTER COLUMN "icon" SET DATA TYPE "public"."enum__articles_v_blocks_market_coverage_actions_icon" USING "icon"::"public"."enum__articles_v_blocks_market_coverage_actions_icon";
  ALTER TABLE "hubs_blocks_trayport_hero_actions" ALTER COLUMN "icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_hubs_blocks_trayport_hero_actions_icon";
  CREATE TYPE "public"."enum_hubs_blocks_trayport_hero_actions_icon" AS ENUM('arrowRight', 'chart', 'europe', 'people', 'play', 'settings');
  ALTER TABLE "hubs_blocks_trayport_hero_actions" ALTER COLUMN "icon" SET DATA TYPE "public"."enum_hubs_blocks_trayport_hero_actions_icon" USING "icon"::"public"."enum_hubs_blocks_trayport_hero_actions_icon";
  ALTER TABLE "hubs_blocks_actions_actions" ALTER COLUMN "icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_hubs_blocks_actions_actions_icon";
  CREATE TYPE "public"."enum_hubs_blocks_actions_actions_icon" AS ENUM('arrowRight', 'chart', 'europe', 'people', 'play', 'settings');
  ALTER TABLE "hubs_blocks_actions_actions" ALTER COLUMN "icon" SET DATA TYPE "public"."enum_hubs_blocks_actions_actions_icon" USING "icon"::"public"."enum_hubs_blocks_actions_actions_icon";
  ALTER TABLE "hubs_blocks_feature_list_items" ALTER COLUMN "action_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_hubs_blocks_feature_list_items_action_icon";
  CREATE TYPE "public"."enum_hubs_blocks_feature_list_items_action_icon" AS ENUM('arrowRight', 'chart', 'europe', 'people', 'play', 'settings');
  ALTER TABLE "hubs_blocks_feature_list_items" ALTER COLUMN "action_icon" SET DATA TYPE "public"."enum_hubs_blocks_feature_list_items_action_icon" USING "action_icon"::"public"."enum_hubs_blocks_feature_list_items_action_icon";
  ALTER TABLE "hubs_blocks_market_coverage_actions" ALTER COLUMN "icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_hubs_blocks_market_coverage_actions_icon";
  CREATE TYPE "public"."enum_hubs_blocks_market_coverage_actions_icon" AS ENUM('arrowRight', 'chart', 'europe', 'people', 'play', 'settings');
  ALTER TABLE "hubs_blocks_market_coverage_actions" ALTER COLUMN "icon" SET DATA TYPE "public"."enum_hubs_blocks_market_coverage_actions_icon" USING "icon"::"public"."enum_hubs_blocks_market_coverage_actions_icon";
  ALTER TABLE "_hubs_v_blocks_trayport_hero_actions" ALTER COLUMN "icon" SET DATA TYPE text;
  DROP TYPE "public"."enum__hubs_v_blocks_trayport_hero_actions_icon";
  CREATE TYPE "public"."enum__hubs_v_blocks_trayport_hero_actions_icon" AS ENUM('arrowRight', 'chart', 'europe', 'people', 'play', 'settings');
  ALTER TABLE "_hubs_v_blocks_trayport_hero_actions" ALTER COLUMN "icon" SET DATA TYPE "public"."enum__hubs_v_blocks_trayport_hero_actions_icon" USING "icon"::"public"."enum__hubs_v_blocks_trayport_hero_actions_icon";
  ALTER TABLE "_hubs_v_blocks_actions_actions" ALTER COLUMN "icon" SET DATA TYPE text;
  DROP TYPE "public"."enum__hubs_v_blocks_actions_actions_icon";
  CREATE TYPE "public"."enum__hubs_v_blocks_actions_actions_icon" AS ENUM('arrowRight', 'chart', 'europe', 'people', 'play', 'settings');
  ALTER TABLE "_hubs_v_blocks_actions_actions" ALTER COLUMN "icon" SET DATA TYPE "public"."enum__hubs_v_blocks_actions_actions_icon" USING "icon"::"public"."enum__hubs_v_blocks_actions_actions_icon";
  ALTER TABLE "_hubs_v_blocks_feature_list_items" ALTER COLUMN "action_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum__hubs_v_blocks_feature_list_items_action_icon";
  CREATE TYPE "public"."enum__hubs_v_blocks_feature_list_items_action_icon" AS ENUM('arrowRight', 'chart', 'europe', 'people', 'play', 'settings');
  ALTER TABLE "_hubs_v_blocks_feature_list_items" ALTER COLUMN "action_icon" SET DATA TYPE "public"."enum__hubs_v_blocks_feature_list_items_action_icon" USING "action_icon"::"public"."enum__hubs_v_blocks_feature_list_items_action_icon";
  ALTER TABLE "_hubs_v_blocks_market_coverage_actions" ALTER COLUMN "icon" SET DATA TYPE text;
  DROP TYPE "public"."enum__hubs_v_blocks_market_coverage_actions_icon";
  CREATE TYPE "public"."enum__hubs_v_blocks_market_coverage_actions_icon" AS ENUM('arrowRight', 'chart', 'europe', 'people', 'play', 'settings');
  ALTER TABLE "_hubs_v_blocks_market_coverage_actions" ALTER COLUMN "icon" SET DATA TYPE "public"."enum__hubs_v_blocks_market_coverage_actions_icon" USING "icon"::"public"."enum__hubs_v_blocks_market_coverage_actions_icon";
  ALTER TABLE "venues_blocks_trayport_hero_actions" ALTER COLUMN "icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_venues_blocks_trayport_hero_actions_icon";
  CREATE TYPE "public"."enum_venues_blocks_trayport_hero_actions_icon" AS ENUM('arrowRight', 'chart', 'europe', 'people', 'play', 'settings');
  ALTER TABLE "venues_blocks_trayport_hero_actions" ALTER COLUMN "icon" SET DATA TYPE "public"."enum_venues_blocks_trayport_hero_actions_icon" USING "icon"::"public"."enum_venues_blocks_trayport_hero_actions_icon";
  ALTER TABLE "venues_blocks_actions_actions" ALTER COLUMN "icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_venues_blocks_actions_actions_icon";
  CREATE TYPE "public"."enum_venues_blocks_actions_actions_icon" AS ENUM('arrowRight', 'chart', 'europe', 'people', 'play', 'settings');
  ALTER TABLE "venues_blocks_actions_actions" ALTER COLUMN "icon" SET DATA TYPE "public"."enum_venues_blocks_actions_actions_icon" USING "icon"::"public"."enum_venues_blocks_actions_actions_icon";
  ALTER TABLE "venues_blocks_feature_list_items" ALTER COLUMN "action_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_venues_blocks_feature_list_items_action_icon";
  CREATE TYPE "public"."enum_venues_blocks_feature_list_items_action_icon" AS ENUM('arrowRight', 'chart', 'europe', 'people', 'play', 'settings');
  ALTER TABLE "venues_blocks_feature_list_items" ALTER COLUMN "action_icon" SET DATA TYPE "public"."enum_venues_blocks_feature_list_items_action_icon" USING "action_icon"::"public"."enum_venues_blocks_feature_list_items_action_icon";
  ALTER TABLE "venues_blocks_market_coverage_actions" ALTER COLUMN "icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_venues_blocks_market_coverage_actions_icon";
  CREATE TYPE "public"."enum_venues_blocks_market_coverage_actions_icon" AS ENUM('arrowRight', 'chart', 'europe', 'people', 'play', 'settings');
  ALTER TABLE "venues_blocks_market_coverage_actions" ALTER COLUMN "icon" SET DATA TYPE "public"."enum_venues_blocks_market_coverage_actions_icon" USING "icon"::"public"."enum_venues_blocks_market_coverage_actions_icon";
  ALTER TABLE "_venues_v_blocks_trayport_hero_actions" ALTER COLUMN "icon" SET DATA TYPE text;
  DROP TYPE "public"."enum__venues_v_blocks_trayport_hero_actions_icon";
  CREATE TYPE "public"."enum__venues_v_blocks_trayport_hero_actions_icon" AS ENUM('arrowRight', 'chart', 'europe', 'people', 'play', 'settings');
  ALTER TABLE "_venues_v_blocks_trayport_hero_actions" ALTER COLUMN "icon" SET DATA TYPE "public"."enum__venues_v_blocks_trayport_hero_actions_icon" USING "icon"::"public"."enum__venues_v_blocks_trayport_hero_actions_icon";
  ALTER TABLE "_venues_v_blocks_actions_actions" ALTER COLUMN "icon" SET DATA TYPE text;
  DROP TYPE "public"."enum__venues_v_blocks_actions_actions_icon";
  CREATE TYPE "public"."enum__venues_v_blocks_actions_actions_icon" AS ENUM('arrowRight', 'chart', 'europe', 'people', 'play', 'settings');
  ALTER TABLE "_venues_v_blocks_actions_actions" ALTER COLUMN "icon" SET DATA TYPE "public"."enum__venues_v_blocks_actions_actions_icon" USING "icon"::"public"."enum__venues_v_blocks_actions_actions_icon";
  ALTER TABLE "_venues_v_blocks_feature_list_items" ALTER COLUMN "action_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum__venues_v_blocks_feature_list_items_action_icon";
  CREATE TYPE "public"."enum__venues_v_blocks_feature_list_items_action_icon" AS ENUM('arrowRight', 'chart', 'europe', 'people', 'play', 'settings');
  ALTER TABLE "_venues_v_blocks_feature_list_items" ALTER COLUMN "action_icon" SET DATA TYPE "public"."enum__venues_v_blocks_feature_list_items_action_icon" USING "action_icon"::"public"."enum__venues_v_blocks_feature_list_items_action_icon";
  ALTER TABLE "_venues_v_blocks_market_coverage_actions" ALTER COLUMN "icon" SET DATA TYPE text;
  DROP TYPE "public"."enum__venues_v_blocks_market_coverage_actions_icon";
  CREATE TYPE "public"."enum__venues_v_blocks_market_coverage_actions_icon" AS ENUM('arrowRight', 'chart', 'europe', 'people', 'play', 'settings');
  ALTER TABLE "_venues_v_blocks_market_coverage_actions" ALTER COLUMN "icon" SET DATA TYPE "public"."enum__venues_v_blocks_market_coverage_actions_icon" USING "icon"::"public"."enum__venues_v_blocks_market_coverage_actions_icon";
  ALTER TABLE "learning_videos_blocks_trayport_hero_actions" ALTER COLUMN "icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_learning_videos_blocks_trayport_hero_actions_icon";
  CREATE TYPE "public"."enum_learning_videos_blocks_trayport_hero_actions_icon" AS ENUM('arrowRight', 'chart', 'europe', 'people', 'play', 'settings');
  ALTER TABLE "learning_videos_blocks_trayport_hero_actions" ALTER COLUMN "icon" SET DATA TYPE "public"."enum_learning_videos_blocks_trayport_hero_actions_icon" USING "icon"::"public"."enum_learning_videos_blocks_trayport_hero_actions_icon";
  ALTER TABLE "learning_videos_blocks_actions_actions" ALTER COLUMN "icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_learning_videos_blocks_actions_actions_icon";
  CREATE TYPE "public"."enum_learning_videos_blocks_actions_actions_icon" AS ENUM('arrowRight', 'chart', 'europe', 'people', 'play', 'settings');
  ALTER TABLE "learning_videos_blocks_actions_actions" ALTER COLUMN "icon" SET DATA TYPE "public"."enum_learning_videos_blocks_actions_actions_icon" USING "icon"::"public"."enum_learning_videos_blocks_actions_actions_icon";
  ALTER TABLE "learning_videos_blocks_feature_list_items" ALTER COLUMN "action_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_learning_videos_blocks_feature_list_items_action_icon";
  CREATE TYPE "public"."enum_learning_videos_blocks_feature_list_items_action_icon" AS ENUM('arrowRight', 'chart', 'europe', 'people', 'play', 'settings');
  ALTER TABLE "learning_videos_blocks_feature_list_items" ALTER COLUMN "action_icon" SET DATA TYPE "public"."enum_learning_videos_blocks_feature_list_items_action_icon" USING "action_icon"::"public"."enum_learning_videos_blocks_feature_list_items_action_icon";
  ALTER TABLE "learning_videos_blocks_market_coverage_actions" ALTER COLUMN "icon" SET DATA TYPE text;
  DROP TYPE "public"."enum_learning_videos_blocks_market_coverage_actions_icon";
  CREATE TYPE "public"."enum_learning_videos_blocks_market_coverage_actions_icon" AS ENUM('arrowRight', 'chart', 'europe', 'people', 'play', 'settings');
  ALTER TABLE "learning_videos_blocks_market_coverage_actions" ALTER COLUMN "icon" SET DATA TYPE "public"."enum_learning_videos_blocks_market_coverage_actions_icon" USING "icon"::"public"."enum_learning_videos_blocks_market_coverage_actions_icon";
  ALTER TABLE "_learning_videos_v_blocks_trayport_hero_actions" ALTER COLUMN "icon" SET DATA TYPE text;
  DROP TYPE "public"."enum__learning_videos_v_blocks_trayport_hero_actions_icon";
  CREATE TYPE "public"."enum__learning_videos_v_blocks_trayport_hero_actions_icon" AS ENUM('arrowRight', 'chart', 'europe', 'people', 'play', 'settings');
  ALTER TABLE "_learning_videos_v_blocks_trayport_hero_actions" ALTER COLUMN "icon" SET DATA TYPE "public"."enum__learning_videos_v_blocks_trayport_hero_actions_icon" USING "icon"::"public"."enum__learning_videos_v_blocks_trayport_hero_actions_icon";
  ALTER TABLE "_learning_videos_v_blocks_actions_actions" ALTER COLUMN "icon" SET DATA TYPE text;
  DROP TYPE "public"."enum__learning_videos_v_blocks_actions_actions_icon";
  CREATE TYPE "public"."enum__learning_videos_v_blocks_actions_actions_icon" AS ENUM('arrowRight', 'chart', 'europe', 'people', 'play', 'settings');
  ALTER TABLE "_learning_videos_v_blocks_actions_actions" ALTER COLUMN "icon" SET DATA TYPE "public"."enum__learning_videos_v_blocks_actions_actions_icon" USING "icon"::"public"."enum__learning_videos_v_blocks_actions_actions_icon";
  ALTER TABLE "_learning_videos_v_blocks_feature_list_items" ALTER COLUMN "action_icon" SET DATA TYPE text;
  DROP TYPE "public"."enum__learning_videos_v_blocks_feature_list_items_action_icon";
  CREATE TYPE "public"."enum__learning_videos_v_blocks_feature_list_items_action_icon" AS ENUM('arrowRight', 'chart', 'europe', 'people', 'play', 'settings');
  ALTER TABLE "_learning_videos_v_blocks_feature_list_items" ALTER COLUMN "action_icon" SET DATA TYPE "public"."enum__learning_videos_v_blocks_feature_list_items_action_icon" USING "action_icon"::"public"."enum__learning_videos_v_blocks_feature_list_items_action_icon";
  ALTER TABLE "_learning_videos_v_blocks_market_coverage_actions" ALTER COLUMN "icon" SET DATA TYPE text;
  DROP TYPE "public"."enum__learning_videos_v_blocks_market_coverage_actions_icon";
  CREATE TYPE "public"."enum__learning_videos_v_blocks_market_coverage_actions_icon" AS ENUM('arrowRight', 'chart', 'europe', 'people', 'play', 'settings');
  ALTER TABLE "_learning_videos_v_blocks_market_coverage_actions" ALTER COLUMN "icon" SET DATA TYPE "public"."enum__learning_videos_v_blocks_market_coverage_actions_icon" USING "icon"::"public"."enum__learning_videos_v_blocks_market_coverage_actions_icon";`)
}
