import { pocScope } from './poc'

export const pilotScope = {
  name: 'pilot',
  roots: [
    ...pocScope.roots,
    {
      legacyId: 2205,
      postType: 'page',
      path: '/company/offices/',
      purpose: 'Office directory',
      archetype: 'page.standard',
      targetOwner: 'pages',
    },
    {
      legacyId: 1926,
      postType: 'page',
      path: '/products/tradesignal/',
      purpose: 'Second product marketing page',
      archetype: 'page.product',
      targetOwner: 'pages',
    },
    {
      legacyId: 7609,
      postType: 'page',
      path: '/resources/faqs/',
      purpose: 'Support FAQ page',
      archetype: 'page.standard',
      targetOwner: 'pages',
    },
    {
      legacyId: 9244,
      postType: 'page',
      path: '/resources/news/',
      purpose: 'News listing',
      archetype: 'page.content-index',
      targetOwner: 'pages',
    },
    {
      legacyId: 10030,
      postType: 'post',
      path: '/event/e-world-2026/',
      purpose: 'Event detail',
      archetype: 'article.full',
      targetOwner: 'articles',
    },
    {
      legacyId: 3311,
      postType: 'page',
      path: '/learning-hub/',
      purpose: 'Learning-video listing',
      archetype: 'page.content-index',
      targetOwner: 'pages',
    },
    {
      legacyId: 8454,
      postType: 'learning-hub-video',
      path: '/learning-hub-video/trading-in-joule/',
      purpose: 'Protected learning-video detail',
      archetype: 'learning-video.public-detail',
      targetOwner: 'learning-videos',
    },
    {
      legacyId: 3363,
      postType: 'venue',
      path: '/venue/eex/',
      purpose: 'Public venue detail',
      archetype: 'venue.public-detail',
      targetOwner: 'venues',
    },
    {
      legacyId: 7589,
      postType: 'page',
      path: '/legal/cookie-policy/',
      purpose: 'Cookie and privacy policy',
      archetype: 'page.legal',
      targetOwner: 'pages',
    },
    {
      legacyId: 2231,
      postType: 'page',
      path: '/resources/market-matrix/',
      purpose: 'Interactive market matrix',
      archetype: 'page.interactive-market-matrix',
      targetOwner: 'pages',
      sourceTitle: 'Market Matrix',
      sourceTemplate: 'layouts/market-matrix.blade.php',
      authoritativeField: 'sections_new',
    },
    {
      legacyId: 5920,
      postType: 'page',
      path: '/resources/markets-map/',
      purpose: 'Interactive regional markets map',
      archetype: 'page.standard',
      targetOwner: 'pages',
      sourceTitle: 'Markets Map',
      sourceTemplate: 'layouts/default-new.blade.php',
      authoritativeField: 'sections_new',
    },
    {
      legacyId: 4737,
      postType: 'page',
      path: '/legal/',
      purpose: 'Legal index',
      archetype: 'page.legal',
      targetOwner: 'pages',
      sourceTitle: 'Legal',
      sourceTemplate: 'layouts/default-new.blade.php',
      authoritativeField: 'sections_new',
    },
    {
      legacyId: 7585,
      postType: 'page',
      path: '/terms-of-use-disclaimer/',
      purpose: 'Terms of use and disclaimer',
      archetype: 'page.legal',
      targetOwner: 'pages',
      sourceTitle: 'Terms of Use and Disclaimer',
      sourceTemplate: 'layouts/default-new.blade.php',
      authoritativeField: 'sections_new',
    },
    {
      legacyId: 4803,
      postType: 'page',
      path: '/legal/legal-notice/',
      purpose: 'Legal notice',
      archetype: 'page.legal',
      targetOwner: 'pages',
      sourceTitle: 'Legal Notice',
      sourceTemplate: 'layouts/article.blade.php',
      authoritativeField: 'sections',
    },
    {
      legacyId: 7573,
      postType: 'page',
      path: '/legal/modern-slavery/',
      purpose: 'Modern slavery statement',
      archetype: 'page.legal',
      targetOwner: 'pages',
      sourceTitle: 'Modern Slavery',
      sourceTemplate: 'layouts/article.blade.php',
      authoritativeField: 'sections',
    },
    {
      legacyId: 5983,
      postType: 'page',
      path: '/regions/asia-pacific/',
      purpose: 'Asia Pacific region page',
      archetype: 'page.standard',
      targetOwner: 'pages',
      sourceTitle: 'Asia Pacific',
      sourceTemplate: 'layouts/default-new.blade.php',
      authoritativeField: 'sections_new',
    },
    {
      legacyId: 2221,
      postType: 'page',
      path: '/regions/north-america/',
      purpose: 'North America region page',
      archetype: 'page.standard',
      targetOwner: 'pages',
      sourceTitle: 'North America',
      sourceTemplate: 'layouts/default-new.blade.php',
      authoritativeField: 'sections_new',
    },
    {
      legacyId: 11475,
      postType: 'page',
      path: '/company/careers/',
      purpose: 'Careers page',
      archetype: 'page.standard',
      targetOwner: 'pages',
      sourceTitle: 'Careers Update',
      sourceTemplate: 'layouts/default-new.blade.php',
      authoritativeField: 'sections_new',
    },
    {
      legacyId: 5981,
      postType: 'page',
      path: '/regions/europe/',
      purpose: 'Europe region page',
      archetype: 'page.standard',
      targetOwner: 'pages',
      sourceTitle: 'Europe',
      sourceTemplate: 'layouts/default-new.blade.php',
      authoritativeField: 'sections_new',
    },
    {
      legacyId: 34,
      postType: 'page',
      path: '/contact/',
      purpose: 'Contact and enquiry page',
      archetype: 'page.standard',
      targetOwner: 'pages',
      sourceTitle: 'Contact',
      sourceTemplate: 'layouts/default-new.blade.php',
      authoritativeField: 'sections_new',
    },
    {
      legacyId: 4031,
      postType: 'page',
      path: '/request-a-demo/',
      purpose: 'Temporary demo-request redirect to managed Contact details',
      archetype: 'redirect.temporary-contact',
      targetOwner: 'redirects',
      sourceTitle: 'Request A Demo',
      sourceTemplate: 'layouts/default-new.blade.php',
      authoritativeField: 'identity-only',
      redirectToLegacyId: 34,
      redirectType: '302',
    },
  ],
  acceptedRouteDependencies: [
    {
      legacyId: 1930,
      postType: 'page',
      path: '/products/data-analytics/',
      purpose: 'Published banner target Page',
      archetype: 'page.product',
      targetOwner: 'pages',
    },
    {
      legacyId: 1940,
      postType: 'page',
      path: '/products/exchange-trading-system/',
      purpose: 'Published banner target Page',
      archetype: 'page.product',
      targetOwner: 'pages',
    },
    {
      legacyId: 4028,
      postType: 'page',
      path: '/resources/lifecycle-information/',
      purpose: 'Published banner target Page',
      archetype: 'page.standard',
      targetOwner: 'pages',
    },
    {
      legacyId: 6773,
      postType: 'page',
      path: '/products/exchange-connectivity/',
      purpose: 'Published banner target Page',
      archetype: 'page.product',
      targetOwner: 'pages',
    },
    {
      legacyId: 11299,
      postType: 'page',
      path: '/eex-news/',
      purpose: 'Published banner CTA Page',
      archetype: 'page.standard',
      targetOwner: 'pages',
    },
  ],
} as const

export type PilotRoot = (typeof pilotScope.roots)[number]
export type AcceptedRouteDependency = (typeof pilotScope.acceptedRouteDependencies)[number]
