// GENERATED FILE — do not edit by hand.
//
// Active WordPress redirect rules, derived from the verified production target plan.
// Regenerate with:
//   corepack pnpm exec tsx migration/scopes/generateProductionRedirects.ts
//
// The exporter does not emit the `redirect` post type, so these come from the inventory's
// source snapshot rather than the extract. `targetOwner` names the collection that owns the
// destination path, so the loader can resolve a managed reference rather than a raw URL.

export const productionRedirects = [
  {
    legacyId: 8362,
    from: '/blog/',
    to: '/resources/news-events-insights/',
    targetOwner: 'pages',
    targetLegacyId: 2235,
    type: '301',
  },
  {
    legacyId: 8340,
    from: '/brokersandexchanges/globalvision-bts/',
    to: '/products/broker-trading-system/',
    targetOwner: 'pages',
    targetLegacyId: 1938,
    type: '301',
  },
  {
    legacyId: 8341,
    from: '/brokersandexchanges/globalvision-ets/',
    to: '/products/exchange-trading-system/',
    targetOwner: 'pages',
    targetLegacyId: 1940,
    type: '301',
  },
  {
    legacyId: 8342,
    from: '/brokersandexchanges/hosted-clearing-links/',
    to: '/products/hosted-clearing-links/',
    targetOwner: 'pages',
    targetLegacyId: 5277,
    type: '301',
  },
  {
    legacyId: 8367,
    from: '/company/',
    to: '/company/about-us/',
    targetOwner: 'pages',
    targetLegacyId: 2203,
    type: '301',
  },
  {
    legacyId: 8364,
    from: '/contact-us/',
    to: '/contact/',
    targetOwner: 'pages',
    targetLegacyId: 34,
    type: '301',
  },
  {
    legacyId: 10918,
    from: '/contact/tradewithus/',
    to: '/contact/',
    targetOwner: 'pages',
    targetLegacyId: 34,
    type: '302',
  },
  {
    legacyId: 8630,
    from: '/education/',
    to: '/contact/',
    targetOwner: 'pages',
    targetLegacyId: 34,
    type: '301',
  },
  {
    legacyId: 8633,
    from: '/events/',
    to: '/resources/news-events-insights/',
    targetOwner: 'pages',
    targetLegacyId: 2235,
    type: '301',
  },
  {
    legacyId: 10233,
    from: '/events/e-world-2026/',
    to: '/event/e-world-2026/',
    targetOwner: 'articles',
    targetLegacyId: 10030,
    type: '301',
  },
  {
    legacyId: 2461,
    from: '/events/eworld-2025/',
    to: '/event/eworld-2025/',
    targetOwner: 'articles',
    targetLegacyId: 2461,
    type: '301',
  },
  {
    legacyId: 2464,
    from: '/events/fia-expo-2024/',
    to: '/event/fia-expo-2024/',
    targetOwner: 'articles',
    targetLegacyId: 2464,
    type: '301',
  },
  {
    legacyId: 10967,
    from: '/events/trayport-spring-party-2026/',
    to: '/event/trayport-spring-party-2026/',
    targetOwner: 'articles',
    targetLegacyId: 10960,
    type: '301',
  },
  {
    legacyId: 2463,
    from: '/events/women-of-silicon-roundabout-2024/',
    to: '/event/women-of-silicon-roundabout-2024/',
    targetOwner: 'articles',
    targetLegacyId: 2463,
    type: '301',
  },
  {
    legacyId: 9156,
    from: '/insights/',
    to: '/resources/news-events-insights/',
    targetOwner: 'pages',
    targetLegacyId: 2235,
    type: '301',
  },
  {
    legacyId: 8365,
    from: '/legal-notice/',
    to: '/legal/legal-notice/',
    targetOwner: 'pages',
    targetLegacyId: 4803,
    type: '301',
  },
  {
    legacyId: 8361,
    from: '/lifecycle-information/',
    to: '/resources/lifecycle-information/',
    targetOwner: 'pages',
    targetLegacyId: 4028,
    type: '301',
  },
  {
    legacyId: 8356,
    from: '/markets/',
    to: '/resources/markets-map/',
    targetOwner: 'pages',
    targetLegacyId: 5920,
    type: '301',
  },
  {
    legacyId: 8624,
    from: '/markets/coal/',
    to: '/markets/oil/',
    targetOwner: 'pages',
    targetLegacyId: 7390,
    type: '301',
  },
  {
    legacyId: 8528,
    from: '/markets/energy-attribute-certificates/',
    to: '/markets/climate/',
    targetOwner: 'pages',
    targetLegacyId: 2213,
    type: '301',
  },
  {
    legacyId: 8625,
    from: '/markets/freight/',
    to: '/markets/bulk-markets/',
    targetOwner: 'pages',
    targetLegacyId: 6888,
    type: '301',
  },
  {
    legacyId: 8355,
    from: '/markets/iron-ore/',
    to: '/markets/bulk-markets/',
    targetOwner: 'pages',
    targetLegacyId: 6888,
    type: '301',
  },
  {
    legacyId: 8353,
    from: '/markets/refined-oil-trading/',
    to: '/markets/oil/',
    targetOwner: 'pages',
    targetLegacyId: 7390,
    type: '301',
  },
  {
    legacyId: 8632,
    from: '/news/',
    to: '/resources/news-events-insights/',
    targetOwner: 'pages',
    targetLegacyId: 2235,
    type: '301',
  },
  {
    legacyId: 8368,
    from: '/office-locations/',
    to: '/company/offices/',
    targetOwner: 'pages',
    targetLegacyId: 2205,
    type: '301',
  },
  {
    legacyId: 10718,
    from: '/products/solutions-providers/',
    to: '/products/third-party-providers/',
    targetOwner: 'pages',
    targetLegacyId: 10490,
    type: '301',
  },
  {
    legacyId: 8877,
    from: '/regions/',
    to: '/regions/europe/',
    targetOwner: 'pages',
    targetLegacyId: 5981,
    type: '301',
  },
  {
    legacyId: 2323,
    from: '/test-redirect/',
    to: '/products/tradesignal/',
    targetOwner: 'pages',
    targetLegacyId: 1926,
    type: '301',
  },
  {
    legacyId: 8346,
    from: '/traders/automated-trading/',
    to: '/products/automated-trading/',
    targetOwner: 'pages',
    targetLegacyId: 2357,
    type: '301',
  },
  {
    legacyId: 8345,
    from: '/traders/autotrader/',
    to: '/products/autotrader/',
    targetOwner: 'pages',
    targetLegacyId: 1928,
    type: '301',
  },
  {
    legacyId: 8350,
    from: '/traders/conformance-testing/',
    to: '/products/conformance-testing/',
    targetOwner: 'pages',
    targetLegacyId: 7541,
    type: '301',
  },
  {
    legacyId: 8347,
    from: '/traders/customer-portal/',
    to: '/products/customer-portal/',
    targetOwner: 'pages',
    targetLegacyId: 1932,
    type: '301',
  },
  {
    legacyId: 8343,
    from: '/traders/data-analytics/',
    to: '/products/data-analytics/',
    targetOwner: 'pages',
    targetLegacyId: 1930,
    type: '301',
  },
  {
    legacyId: 8349,
    from: '/traders/implied-price-calculator/',
    to: '/products/implied-price-calculator/',
    targetOwner: 'pages',
    targetLegacyId: 1936,
    type: '301',
  },
  {
    legacyId: 8348,
    from: '/traders/internal-marketplace/',
    to: '/products/internal-marketplace/',
    targetOwner: 'pages',
    targetLegacyId: 2359,
    type: '301',
  },
  {
    legacyId: 8339,
    from: '/traders/joule/',
    to: '/products/joule/',
    targetOwner: 'pages',
    targetLegacyId: 1924,
    type: '301',
  },
  {
    legacyId: 8344,
    from: '/traders/tradesignal/',
    to: '/products/tradesignal/',
    targetOwner: 'pages',
    targetLegacyId: 1926,
    type: '301',
  },
  {
    legacyId: 8900,
    from: '/traders/tradesignal/equilla/',
    to: '/products/tradesignal/',
    targetOwner: 'pages',
    targetLegacyId: 1926,
    type: '301',
  },
] as const
