import type { IconDefinition } from '@fortawesome/fontawesome-svg-core'
import {
  faArrowRight,
  faBars,
  faCheck,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faCirclePlay,
  faEllipsis,
  faEnvelope,
  faForward,
  faImage,
  faGear,
  faMinus,
  faPause,
  faPhone,
  faPlay,
  faPlus,
  faSpinnerThird,
  faXmark,
} from '@awesome.me/kit-9e17af3472/icons/classic/solid'
import {
  faArrowTrendUp,
  faChartLine,
  faChartMixed,
  faClock,
  faLightbulb,
  faScanner,
} from '@awesome.me/kit-9e17af3472/icons/classic/light'
import {
  faMagnifyingGlass,
  faMagnifyingGlassChart,
} from '@awesome.me/kit-9e17af3472/icons/sharp/regular'
import { faAngleDown } from '@awesome.me/kit-9e17af3472/icons/sharp-duotone/light'
import {
  faAddressCard,
  faBuildings,
  faEarthAmericas,
  faEarthAsia,
  faEarthEurope,
  faEnvelope as faSharpEnvelope,
  faFilePen,
  faFireFlame as faGas,
  faGridRound4,
  faHandshake,
  faIndustry as faEmissions,
  faLightbulb as faPowerVolume,
  faLightbulbCfl as faPower,
} from '@awesome.me/kit-9e17af3472/icons/sharp/solid'
import {
  faArrowUpRightFromSquare,
  faArrowsSpin,
  faBallot,
  faBuildingLock,
  faCalculatorSimple,
  faCalendarDays,
  faChartCandlestick,
  faChartNetwork,
  faChartPie,
  faChartUser,
  faChartWaterfall,
  faCode,
  faCodeCompare,
  faCoins,
  faDiagramProject,
  faEarth,
  faEarthAmericas as faNavigationEarthAmericas,
  faEarthAsia as faNavigationEarthAsia,
  faEarthEurope as faNavigationEarthEurope,
  faFile,
  faFileCsv,
  faFireFlameSimple,
  faHexagonNodes,
  faList,
  faLocationDot,
  faLock,
  faMapLocationDot,
  faMessageQuote,
  faMessages,
  faMoneyBillTrendUp,
  faMonitorWaveform,
  faNewspaper,
  faOilWell,
  faPeopleGroup,
  faSeedling,
  faShield,
  faUsers,
  faVideo,
} from '@awesome.me/kit-9e17af3472/icons/sharp-duotone/solid'
import { faLinkedin, faXTwitter } from '@fortawesome/free-brands-svg-icons'

/**
 * Semantic, deliberately bounded icon registry.
 *
 * Application components and Payload adapters use these names rather than
 * Font Awesome package names. This keeps icon changes reversible, prevents a
 * CMS string from loading an arbitrary icon, and allows the bundler to retain
 * only definitions used by the application.
 */
export const appIcons = {
  arrowRight: faArrowRight,
  asiaPacific: faNavigationEarthAsia,
  ballot: faBallot,
  buildingSecurity: faBuildingLock,
  bulkMarkets: faFireFlameSimple,
  calculator: faCalculatorSimple,
  calendar: faCalendarDays,
  candlestickChart: faChartCandlestick,
  careers: faHandshake,
  chart: faChartMixed,
  chartLine: faChartLine,
  check: faCheck,
  chevronDown: faAngleDown,
  chevronLeft: faChevronLeft,
  chevronRight: faChevronRight,
  chevronUp: faChevronUp,
  clock: faClock,
  close: faXmark,
  climate: faSeedling,
  code: faCode,
  companyProfile: faAddressCard,
  compare: faCodeCompare,
  connections: faDiagramProject,
  connectivity: faHexagonNodes,
  contact: faSharpEnvelope,
  csvFile: faFileCsv,
  demo: faMonitorWaveform,
  email: faEnvelope,
  europe: faNavigationEarthEurope,
  externalLink: faArrowUpRightFromSquare,
  file: faFile,
  forward: faForward,
  emissions: faEmissions,
  gas: faGas,
  image: faImage,
  insight: faMagnifyingGlassChart,
  lightbulb: faLightbulb,
  lifecycle: faArrowsSpin,
  linkedin: faLinkedin,
  list: faList,
  location: faLocationDot,
  lock: faLock,
  legalDocument: faFilePen,
  map: faMapLocationDot,
  marketAccess: faMoneyBillTrendUp,
  menu: faBars,
  marketMatrix: faGridRound4,
  messages: faMessages,
  metals: faCoins,
  minus: faMinus,
  more: faEllipsis,
  network: faChartNetwork,
  news: faNewspaper,
  northAmerica: faNavigationEarthAmericas,
  oil: faOilWell,
  offices: faBuildings,
  pause: faPause,
  phone: faPhone,
  play: faPlay,
  playCircle: faCirclePlay,
  plus: faPlus,
  people: faPeopleGroup,
  pieChart: faChartPie,
  power: faPower,
  powerVolume: faPowerVolume,
  quote: faMessageQuote,
  regionAsiaPacific: faEarthAsia,
  regionEurope: faEarthEurope,
  regionNorthAmerica: faEarthAmericas,
  scan: faScanner,
  settings: faGear,
  search: faMagnifyingGlass,
  searchInsight: faMagnifyingGlassChart,
  spinner: faSpinnerThird,
  shield: faShield,
  trend: faArrowTrendUp,
  tradingScreen: faChartUser,
  users: faUsers,
  video: faVideo,
  waterfallChart: faChartWaterfall,
  world: faEarth,
  x: faXTwitter,
} as const satisfies Record<string, IconDefinition>

export type AppIconName = keyof typeof appIcons

export const featureIconNames = [
  'lightbulb',
  'trend',
  'clock',
  'chart',
  'scan',
] as const satisfies readonly AppIconName[]

export type FeatureIconName = (typeof featureIconNames)[number]
